version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: arisutalk-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
