interface ViteTypeOptions {
    strictImportMetaEnv: unknown;
}

interface ImportMetaEnv {
    // generated by scripts/versionResolver.ts
    /**
     * The version channel of the app.
     * prod, dev, spark
     */
    readonly VITE_VERSION_CHANNEL: string;
    /**
     * The version name of the app.
     */
    readonly VITE_VERSION_NAME: string;
    /**
     * The version url of the app.
     */
    readonly VITE_VERSION_URL: string;
    /**
     * Backend phonebook API base URL.
     */
    readonly VITE_PHONEBOOK_BASE_URL?: string;

    // Vitest environment variable
    /**
     * Indicates if the code is running in a Vitest testing environment.
     */
    readonly VITEST?: boolean;
    /**
     * Indicates if Vitest is running in browser mode.
     * "false" on non-testing or node mode.
     */
    readonly VITEST_BROWSER_MODE: "true" | "false";
}

interface ImportMeta {
    readonly env: ImportMetaEnv;
}

// No SharedArrayBuffer, we can't use it due to browser
interface SharedArrayBuffer {
    readonly [Symbol.toStringTag]: "SharedArrayBuffer";
}
type ArrayBufferLike = ArrayBuffer;
// eslint-disable-next-line no-var
declare var SharedArrayBuffer: never;
