interface ViteTypeOptions {
    strictImportMetaEnv: unknown;
}

interface ImportMetaEnv {
    // generated by scripts/versionResolver.ts
    /**
     * The version channel of the app.
     * prod, dev, spark
     */
    readonly VITE_VERSION_CHANNEL: string;
    /**
     * The version name of the app.
     */
    readonly VITE_VERSION_NAME: string;
    /**
     * The version url of the app.
     */
    readonly VITE_VERSION_URL: string;

    // Vitest environment variable
    /**
     * Indicates if the code is running in a Vitest testing environment.
     */
    readonly VITEST?: boolean;
}

interface ImportMeta {
    readonly env: ImportMetaEnv;
}
