/**
 * Secure Storage Manager for API keys
 * Handles encryption, storage, and retrieval of sensitive data
 */

import { encryptText, decryptText, generateMasterPassword } from "./crypto";
import { loadFromBrowserStorage, saveToBrowserStorage } from "../../storage";
import { t } from "$root/i18n";
import { getStorageKey } from "./storageKey";
import type { APISettings } from "../../defaults";

const STORAGE_KEYS = {
    ENCRYPTED_API_CONFIGS: getStorageKey("personaChat_encryptedApiConfigs_v1"),
    MASTER_PASSWORD_HINT: getStorageKey("personaChat_masterPasswordHint_v1"),
    SESSION_MASTER_PASSWORD: getStorageKey("personaChat_sessionMasterPassword"), // sessionStorage only
    ENCRYPTION_ENABLED: getStorageKey("personaChat_encryptionEnabled_v1"),
};

/**
 * Secure Storage Manager class
 */
export class SecureStorageManager {
    private masterPassword: string | null;
    public encryptionEnabled: boolean;

    constructor() {
        this.masterPassword = null;
        this.encryptionEnabled = false;
    }

    /**
     * Initialize secure storage - always enabled
     */
    async initialize(): Promise<boolean> {
        try {
            // Check if this is first time setup
            const hasExistingEncryption = await loadFromBrowserStorage<boolean>(
                STORAGE_KEYS.ENCRYPTION_ENABLED,
                false
            );

            if (!hasExistingEncryption) {
                // First time setup - enable encryption automatically
                const autoPassword = this.generateMasterPassword();
                await this.setupEncryption(
                    autoPassword,
                    t("secureStorage.autoGeneratedHint")
                );
            } else {
                // Existing setup - restore from session or regenerate
                this.encryptionEnabled = true;
                this.masterPassword = sessionStorage.getItem(
                    STORAGE_KEYS.SESSION_MASTER_PASSWORD
                );

                if (!this.masterPassword) {
                    // Session expired, regenerate password (user won't notice)
                    const autoPassword = this.generateMasterPassword();
                    this.masterPassword = autoPassword;
                    sessionStorage.setItem(
                        STORAGE_KEYS.SESSION_MASTER_PASSWORD,
                        autoPassword
                    );
                }
            }

            return true;
        } catch (error) {
            console.error("Failed to initialize secure storage:", error);
            return false;
        }
    }

    /**
     * Setup encryption with master password
     */
    async setupEncryption(masterPassword: string, hint: string = ""): Promise<boolean> {
        try {
            // Test encryption with a dummy value
            await encryptText("test", masterPassword);

            this.masterPassword = masterPassword;
            this.encryptionEnabled = true;

            // Store master password in session (temporary)
            sessionStorage.setItem(
                STORAGE_KEYS.SESSION_MASTER_PASSWORD,
                masterPassword
            );

            // Store hint and encryption flag
            saveToBrowserStorage(STORAGE_KEYS.MASTER_PASSWORD_HINT, hint);
            saveToBrowserStorage(STORAGE_KEYS.ENCRYPTION_ENABLED, true);

            return true;
        } catch (error) {
            console.error("Failed to setup encryption:", error);
            throw new Error(t("secureStorage.setupEncryptionFailed"));
        }
    }

    /**
     * Save encrypted API configurations
     */
    async saveApiConfigs(apiConfigs: APISettings['apiConfigs']): Promise<void> {
        if (!this.masterPassword) {
            console.warn(t("secureStorage.noMasterPasswordForEncryption"));
            return;
        }

        try {
            const jsonString = JSON.stringify(apiConfigs);
            const encrypted = await encryptText(
                jsonString,
                this.masterPassword
            );
            saveToBrowserStorage(STORAGE_KEYS.ENCRYPTED_API_CONFIGS, encrypted);
        } catch (error) {
            console.error("Failed to save encrypted API configs:", error);
            throw new Error(t("secureStorage.saveApiConfigsFailed"));
        }
    }

    /**
     * Load and decrypt API configurations
     */
    async loadApiConfigs(): Promise<Partial<APISettings['apiConfigs']>> {
        if (!this.masterPassword) {
            console.warn(t("secureStorage.noMasterPasswordForDecryption"));
            return {};
        }

        try {
            const encrypted = await loadFromBrowserStorage<string | null>(
                STORAGE_KEYS.ENCRYPTED_API_CONFIGS,
                null
            );

            if (!encrypted) {
                return {};
            }

            const jsonString = await decryptText(
                encrypted,
                this.masterPassword
            );
            return JSON.parse(jsonString) as Partial<APISettings['apiConfigs']>;
        } catch (error) {
            console.error(t("secureStorage.loadApiConfigsFailed"), error);
            return {};
        }
    }

    /**
     * Get password hint
     */
    async getPasswordHint(): Promise<string> {
        return await loadFromBrowserStorage<string>(
            STORAGE_KEYS.MASTER_PASSWORD_HINT,
            ""
        );
    }

    /**
     * Generate a secure master password
     */
    generateMasterPassword(): string {
        return generateMasterPassword();
    }

    /**
     * Clear master password (reset)
     */
    clearMasterPassword() {
        this.masterPassword = null;
        this.encryptionEnabled = false;
    }
}

// Export singleton instance
export const secureStorage = new SecureStorageManager();
