<script module>
    import PlaceholderIcon from "phosphor-svelte/lib/PlaceholderIcon";

    import GearIcon from "phosphor-svelte/lib/GearIcon";
    import XIcon from "phosphor-svelte/lib/XIcon";

    import type { Component } from "svelte";

    export type Subpage<Props extends Record<string, any>> = {
        kind: string;
        panel: Component<Props>;
        icon: Component;
        title: string;
        label: string;
        text: string;
    };

    import { marked } from "marked";
    import DOMPurify from "dompurify";

    const markedOption: { async: false } = { async: false };

    function compileMarkdown(text: string) {
        return DOMPurify.sanitize(marked.parse(text, markedOption));
    }

    type PreloadTemplate<T extends Record<string, any>> = {
        contents?:
            | {
                  type: "none";
              }
            | {
                  type: "markdown";
                  text: string;
              }
            | {
                  type: "component";
                  component: Component<T>;
              };
        icon?: Component;
        label?: string;
    };

    /** This type is intended for internal use only. Do not use it for arbitrary purposes. */
    type Page<Props extends Record<string, any>> = (
        | {
              /** Represents an empty page. Renders nothing. */
              type: "none";
          }
        | {
              /** Represents a Markdown document. */
              type: "markdown";
              /**
               * `text` must be valid GFM (GitHub-Flavored Markdown).
               * Security note: `DOMPurify.sanitize()` is called internally, so
               * unsupported or potentially unsafe HTML may be removed.
               */
              text: string;
          }
        | {
              /** Renders an arbitrary component. */
              type: "component";
              /** The component's props used for rendering must share a common type. */
              component: Component<Props>;
          }
    ) & {
        id: string;
        index: number;
    };

    /**
        Preloads the data required by SettingsDialog for rendering.
        Note: This function must be invoked at module scope.

        The value returned by this function is referred to as the `preloaded` dataset. Developers generally do not need to use it. In exceptional cases, it can be used to specify an initial value, as shown in `let activeId = $state(preloaded.tabList[0]?.id ?? "");`.
    */
    export function preload<T extends Record<string, any>>(templates: PreloadTemplate<T>[]) {
        const tabList: {
            /** A random string generated by `crypto.randomUUID()`. */
            id: string;
            /** The name of the tab. */
            label: string;
            /** The tab's icon. */
            icon: Component;
        }[] = [];

        const pageMap: Record<string, Page<T>> = {};

        for (const template of templates) {
            const id = crypto.randomUUID();

            const contents = template.contents;
            const index = tabList.length;

            if (!contents || contents.type === "none") {
                pageMap[id] = { id, index, type: "none" };
            } else if (contents.type === "markdown") {
                pageMap[id] = { id, index, type: "markdown", text: compileMarkdown(contents.text) };
            } else if (contents.type === "component") {
                pageMap[id] = { id, index, type: "component", component: contents.component };
            }

            tabList.push({
                id,
                label: template.label ?? "Empty",
                icon: template.icon ?? PlaceholderIcon,
            });
        }

        return { tabList, pageMap };
    }
</script>

<script lang="ts" generics="TContext = never">
    // DO NOT REMOVE
    type TProps = { context: () => TContext };

    let {
        id = "untitled-" + crypto.randomUUID(),
        title = "Untitled",
        preloaded,
        onOpen = () => null,
        onClose = () => null,
        onTabChange,
        activeId,
        settingsModalContext,
        self = $bindable(),
    }: {
        id?: string;
        title?: string;
        preloaded: {
            tabList: {
                id: string;
                label: string;
                icon: Component;
            }[];
            pageMap: Record<string, Page<TProps>>;
        };
        onOpen?: () => void;
        onClose?: () => void;
        onTabChange: (kind: string) => void;
        activeId: string;
        settingsModalContext: () => TContext;
        self?: HTMLDialogElement;
    } = $props();

    let { tabList, pageMap } = $derived(preloaded);

    function handleBackdropClick(e: MouseEvent) {
        if (e.target === self) {
            onClose();
        }
    }

    function onAttach(dialog: HTMLDialogElement) {
        dialog.showModal();
        onOpen();
    }
</script>

{#snippet Tab(id: string, Icon: Component, label: string, isActive: boolean)}
    <li>
        <button
            class="flex gap-2 rounded-lg"
            class:active={isActive}
            onclick={() => onTabChange(id)}
            aria-label={label}
        >
            <Icon size={18} />
            {label}
        </button>
    </li>
{/snippet}

{#snippet Panel(Comp: Component<TProps>)}
    <div class="space-y-6">
        <h3 class="text-lg font-semibold">{title}</h3>

        <Comp context={settingsModalContext} />
    </div>
{/snippet}

<dialog
    bind:this={self}
    class="modal"
    onclose={onClose}
    onclick={handleBackdropClick}
    aria-labelledby="{id}-settings-title"
    {@attach onAttach}
>
    <div
        class="modal-box w-11/12 max-w-5xl h-[80vh] p-0 flex flex-col overflow-hidden bg-base-100 text-base-content shadow-2xl"
    >
        <!-- Header -->
        <header
            class="flex items-center justify-between p-4 border-b border-base-300/50 bg-base-200/80"
        >
            <h2
                id="{id}-settings-title"
                class="text-xl font-bold flex items-center gap-2 tracking-tight"
            >
                <GearIcon size={24} />
                {title} Settings
            </h2>
            <button
                class="btn btn-ghost btn-sm btn-square hover:bg-base-300/50"
                onclick={onClose}
                aria-label="Close"
            >
                <XIcon size={20} />
            </button>
        </header>

        <div class="flex flex-1 overflow-hidden">
            <!-- Sidebar -->
            <aside class="w-56 bg-base-200/60 p-3 overflow-y-auto border-r border-base-300/50">
                <ul class="menu w-full p-0 gap-1">
                    {#each tabList as tab (tab.id)}
                        {@const isActive = tab.id === activeId}
                        {@render Tab(tab.id, tab.icon, tab.label, isActive)}
                    {/each}
                </ul>
            </aside>

            <!-- Main Panel -->
            <main class="flex-1 p-6 overflow-y-auto bg-base-100">
                {#if pageMap[activeId].type === "none"}
                    <div></div>
                {:else if pageMap[activeId].type === "markdown"}
                    <div class="prose prose-compact prose-invert prose-sm prose-gray max-w-[80ch]">
                        {@html pageMap[activeId].text}
                    </div>
                {:else if pageMap[activeId].type === "component"}
                    {@render Panel(pageMap[activeId].component)}
                {/if}
            </main>
        </div>

        <!-- Footer -->
        <div class="modal-action p-4 border-t border-base-300/50 bg-base-200/60 m-0">
            <span class="text-sm text-base-content/50 flex-1">Changes are saved automatically</span>
            <button class="btn btn-primary shadow-md" onclick={onClose}>Close</button>
        </div>
    </div>
</dialog>

<style>
    aside::-webkit-scrollbar {
        width: 4px;
    }
    aside::-webkit-scrollbar-thumb {
        background-color: var(--fallback-bc, oklch(var(--bc) / 0.2));
        border-radius: 4px;
    }
</style>
